"""Git integration service for project version control."""

import os
import subprocess
from typing import Optional
from datetime import datetime


class GitService:
    """Manages Git operations for generated projects."""

    @staticmethod
    def init_repo(project_path: str) -> bool:
        """Initialize a Git repository in the project directory.

        Args:
            project_path: Absolute path to the generated project.

        Returns:
            True if initialization succeeded.
        """
        if not os.path.isdir(project_path):
            return False

        try:
            subprocess.run(
                ["git", "init"],
                cwd=project_path,
                check=True,
                capture_output=True,
                text=True,
            )

            # Create a .gitignore with sensible defaults
            gitignore_path = os.path.join(project_path, ".gitignore")
            if not os.path.exists(gitignore_path):
                with open(gitignore_path, "w", encoding="utf-8") as f:
                    f.write(
                        "# -- Auto-generated by Software Foundry --\n"
                        "__pycache__/\n"
                        "*.pyc\n"
                        ".env\n"
                        "node_modules/\n"
                        "dist/\n"
                        ".venv/\n"
                        "venv/\n"
                        "*.egg-info/\n"
                    )

            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False

    @staticmethod
    def commit_all(
        project_path: str,
        message: Optional[str] = None,
    ) -> bool:
        """Stage all files and create a commit with a conventional message.

        Args:
            project_path: Absolute path to the project repo.
            message: Optional commit message override.

        Returns:
            True if the commit succeeded.
        """
        if message is None:
            timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
            message = f"feat: initial project scaffold generated by Software Foundry ({timestamp})"

        try:
            subprocess.run(
                ["git", "add", "."],
                cwd=project_path,
                check=True,
                capture_output=True,
                text=True,
            )

            # Configure a local user for the commit if not already set
            subprocess.run(
                ["git", "config", "user.email", "foundry@autonomous.local"],
                cwd=project_path,
                capture_output=True,
                text=True,
            )
            subprocess.run(
                ["git", "config", "user.name", "Software Foundry"],
                cwd=project_path,
                capture_output=True,
                text=True,
            )

            subprocess.run(
                ["git", "commit", "-m", message],
                cwd=project_path,
                check=True,
                capture_output=True,
                text=True,
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False


# Module-level convenience instance
git_service = GitService()
