"""Git repository management for the Autonomous Software Foundry.

This module provides comprehensive Git integration including:
- Repository initialization and configuration
- Atomic commits with conventional commit messages
- Branch management for feature development
- File change tracking
- Merge conflict detection and handling
- Tag generation for releases
"""

import os
import subprocess
import logging
from typing import List, Optional, Dict, Tuple
from datetime import datetime
from pathlib import Path
from enum import Enum

logger = logging.getLogger(__name__)


class CommitType(str, Enum):
    """Conventional commit types."""
    FEAT = "feat"
    FIX = "fix"
    REFACTOR = "refactor"
    DOCS = "docs"
    TEST = "test"
    CHORE = "chore"
    STYLE = "style"
    PERF = "perf"


class MergeStrategy(str, Enum):
    """Merge strategies for conflict resolution."""
    OURS = "ours"
    THEIRS = "theirs"
    RECURSIVE = "recursive"


class GitManager:
    """Manages Git operations for autonomous software development."""

    def __init__(self, repo_path: str):
        """Initialize Git manager for a repository.
        
        Args:
            repo_path: Path to the Git repository
        """
        self.repo_path = Path(repo_path).resolve()
        self.default_user_name = "Software Foundry"
        self.default_user_email = "foundry@autonomous.local"

    def _run_git_command(
        self, 
        args: List[str], 
        check: bool = True,
        capture_output: bool = True
    ) -> subprocess.CompletedProcess:
        """Run a Git command in the repository.
        
        Args:
            args: Git command arguments
            check: Whether to raise exception on non-zero exit
            capture_output: Whether to capture stdout/stderr
            
        Returns:
            CompletedProcess instance
            
        Raises:
            subprocess.CalledProcessError: If command fails and check=True
        """
        try:
            result = subprocess.run(
                ["git"] + args,
                cwd=str(self.repo_path),
                check=check,
                capture_output=capture_output,
                text=True
            )
            return result
        except subprocess.CalledProcessError as e:
            logger.error(f"Git command failed: {' '.join(args)}")
            logger.error(f"Error: {e.stderr}")
            raise

    def initialize_repository(
        self,
        initial_branch: str = "main",
        create_gitignore: bool = True,
        create_gitattributes: bool = True
    ) -> bool:
        """Initialize a Git repository with proper configuration.
        
        Implements Requirement 18.1: Initialize Git repository with .gitignore,
        .gitattributes, and initial commit.
        
        Args:
            initial_branch: Name of the initial branch (default: main)
            create_gitignore: Whether to create a default .gitignore
            create_gitattributes: Whether to create a default .gitattributes
            
        Returns:
            True if initialization succeeded, False otherwise
        """
        try:
            # Check if already a git repository
            if (self.repo_path / ".git").exists():
                logger.info(f"Repository already initialized at {self.repo_path}")
                return True

            # Initialize repository
            self._run_git_command(["init", "-b", initial_branch])
            logger.info(f"Initialized Git repository at {self.repo_path}")

            # Configure user
            self._configure_user()

            # Create .gitignore
            if create_gitignore:
                self._create_gitignore()

            # Create .gitattributes
            if create_gitattributes:
                self._create_gitattributes()

            # Create initial commit
            if self._has_changes():
                self.create_commit(
                    CommitType.CHORE,
                    "initialize repository with configuration files"
                )

            return True

        except Exception as e:
            logger.error(f"Failed to initialize repository: {e}")
            return False

    def _configure_user(self) -> None:
        """Configure Git user for the repository."""
        self._run_git_command(
            ["config", "user.name", self.default_user_name],
            check=False
        )
        self._run_git_command(
            ["config", "user.email", self.default_user_email],
            check=False
        )

    def _create_gitignore(self) -> None:
        """Create a comprehensive .gitignore file."""
        gitignore_content = """# Auto-generated by Autonomous Software Foundry

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
.pytest_cache/
.coverage
htmlcov/
.tox/
.venv/
venv/
ENV/
env/

# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm
.eslintcache

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store

# Environment
.env
.env.local
.env.*.local

# Logs
logs/
*.log

# Database
*.db
*.sqlite
*.sqlite3

# OS
Thumbs.db
"""
        gitignore_path = self.repo_path / ".gitignore"
        gitignore_path.write_text(gitignore_content)
        logger.info("Created .gitignore")

    def _create_gitattributes(self) -> None:
        """Create a .gitattributes file for consistent line endings."""
        gitattributes_content = """# Auto-generated by Autonomous Software Foundry

# Auto detect text files and perform LF normalization
* text=auto

# Source code
*.py text eol=lf
*.js text eol=lf
*.ts text eol=lf
*.jsx text eol=lf
*.tsx text eol=lf
*.json text eol=lf
*.yml text eol=lf
*.yaml text eol=lf
*.md text eol=lf
*.sh text eol=lf

# Windows scripts
*.bat text eol=crlf
*.cmd text eol=crlf
*.ps1 text eol=crlf

# Binary files
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.ico binary
*.pdf binary
*.zip binary
*.tar.gz binary
"""
        gitattributes_path = self.repo_path / ".gitattributes"
        gitattributes_path.write_text(gitattributes_content)
        logger.info("Created .gitattributes")

    def create_commit(
        self,
        commit_type: CommitType,
        description: str,
        scope: Optional[str] = None,
        body: Optional[str] = None,
        breaking: bool = False,
        files: Optional[List[str]] = None
    ) -> bool:
        """Create an atomic commit with conventional commit format.
        
        Implements Requirement 18.2: Create atomic commits with conventional
        commit format (feat:, fix:, refactor:, etc.)
        
        Args:
            commit_type: Type of commit (feat, fix, refactor, etc.)
            description: Short description of the change
            scope: Optional scope of the change
            body: Optional detailed description
            breaking: Whether this is a breaking change
            files: Optional list of specific files to commit (None = all changes)
            
        Returns:
            True if commit succeeded, False otherwise
        """
        try:
            # Stage files
            if files:
                for file in files:
                    self._run_git_command(["add", file])
            else:
                self._run_git_command(["add", "."])

            # Check if there are changes to commit
            if not self._has_staged_changes():
                logger.info("No changes to commit")
                return False

            # Build commit message
            message = self._build_commit_message(
                commit_type, description, scope, body, breaking
            )

            # Create commit
            self._run_git_command(["commit", "-m", message])
            logger.info(f"Created commit: {message.split(chr(10))[0]}")
            return True

        except Exception as e:
            logger.error(f"Failed to create commit: {e}")
            return False

    def _build_commit_message(
        self,
        commit_type: CommitType,
        description: str,
        scope: Optional[str],
        body: Optional[str],
        breaking: bool
    ) -> str:
        """Build a conventional commit message."""
        # Header
        header = f"{commit_type.value}"
        if scope:
            header += f"({scope})"
        if breaking:
            header += "!"
        header += f": {description}"

        # Full message
        message = header
        if body:
            message += f"\n\n{body}"
        if breaking and body:
            message += "\n\nBREAKING CHANGE: This commit contains breaking changes."

        return message

    def create_feature_branch(
        self,
        agent_name: str,
        feature_description: str,
        base_branch: str = "main"
    ) -> Optional[str]:
        """Create a feature branch following naming convention.
        
        Implements Requirement 18.3: Create feature branches following
        `foundry/<agent-name>/<feature-description>` convention.
        
        Args:
            agent_name: Name of the agent creating the branch
            feature_description: Description of the feature
            base_branch: Base branch to branch from
            
        Returns:
            Branch name if successful, None otherwise
        """
        try:
            # Sanitize feature description for branch name
            sanitized_desc = feature_description.lower()
            sanitized_desc = sanitized_desc.replace(" ", "-")
            sanitized_desc = "".join(c for c in sanitized_desc if c.isalnum() or c == "-")

            # Build branch name
            branch_name = f"foundry/{agent_name}/{sanitized_desc}"

            # Ensure we're on the base branch
            self._run_git_command(["checkout", base_branch])

            # Create and checkout new branch
            self._run_git_command(["checkout", "-b", branch_name])
            logger.info(f"Created feature branch: {branch_name}")

            return branch_name

        except Exception as e:
            logger.error(f"Failed to create feature branch: {e}")
            return None

    def get_current_branch(self) -> Optional[str]:
        """Get the name of the current branch.
        
        Returns:
            Current branch name or None if error
        """
        try:
            result = self._run_git_command(["branch", "--show-current"])
            return result.stdout.strip()
        except Exception as e:
            logger.error(f"Failed to get current branch: {e}")
            return None

    def switch_branch(self, branch_name: str) -> bool:
        """Switch to a different branch.
        
        Args:
            branch_name: Name of the branch to switch to
            
        Returns:
            True if successful, False otherwise
        """
        try:
            self._run_git_command(["checkout", branch_name])
            logger.info(f"Switched to branch: {branch_name}")
            return True
        except Exception as e:
            logger.error(f"Failed to switch branch: {e}")
            return False

    def get_changed_files(self) -> List[str]:
        """Get list of files with uncommitted changes.
        
        Implements Requirement 18.4: Track file changes for atomic commits.
        
        Returns:
            List of file paths with changes
        """
        try:
            # Get modified files
            result = self._run_git_command(["status", "--porcelain"])
            lines = result.stdout.strip().split("\n")
            
            files = []
            for line in lines:
                if line:
                    # Parse status format: "XY filename"
                    status = line[:2]
                    filename = line[3:]
                    files.append(filename)
            
            return files

        except Exception as e:
            logger.error(f"Failed to get changed files: {e}")
            return []

    def has_merge_conflicts(self) -> bool:
        """Check if there are merge conflicts.
        
        Implements Requirement 18.5: Detect merge conflicts.
        
        Returns:
            True if conflicts exist, False otherwise
        """
        try:
            result = self._run_git_command(
                ["diff", "--name-only", "--diff-filter=U"],
                check=False
            )
            conflicted_files = result.stdout.strip()
            return bool(conflicted_files)

        except Exception as e:
            logger.error(f"Failed to check for conflicts: {e}")
            return False

    def get_conflicted_files(self) -> List[str]:
        """Get list of files with merge conflicts.
        
        Returns:
            List of file paths with conflicts
        """
        try:
            result = self._run_git_command(
                ["diff", "--name-only", "--diff-filter=U"],
                check=False
            )
            files = result.stdout.strip().split("\n")
            return [f for f in files if f]

        except Exception as e:
            logger.error(f"Failed to get conflicted files: {e}")
            return []

    def attempt_auto_merge(
        self,
        branch_name: str,
        strategy: MergeStrategy = MergeStrategy.RECURSIVE
    ) -> Tuple[bool, Optional[str]]:
        """Attempt automatic merge conflict resolution.
        
        Implements Requirement 18.5: Attempt automatic resolution using
        three-way merge strategies.
        
        Args:
            branch_name: Branch to merge
            strategy: Merge strategy to use
            
        Returns:
            Tuple of (success, error_message)
        """
        try:
            # Attempt merge with strategy
            strategy_flag = f"-X{strategy.value}" if strategy != MergeStrategy.RECURSIVE else ""
            
            args = ["merge", branch_name]
            if strategy_flag:
                args.append(strategy_flag)
            
            result = self._run_git_command(args, check=False)
            
            if result.returncode == 0:
                logger.info(f"Successfully merged {branch_name}")
                return True, None
            else:
                # Check for conflicts
                if self.has_merge_conflicts():
                    conflicted = self.get_conflicted_files()
                    error_msg = f"Merge conflicts in: {', '.join(conflicted)}"
                    logger.warning(error_msg)
                    return False, error_msg
                else:
                    return False, result.stderr

        except Exception as e:
            logger.error(f"Failed to merge: {e}")
            return False, str(e)

    def abort_merge(self) -> bool:
        """Abort an in-progress merge.
        
        Returns:
            True if successful, False otherwise
        """
        try:
            self._run_git_command(["merge", "--abort"])
            logger.info("Aborted merge")
            return True
        except Exception as e:
            logger.error(f"Failed to abort merge: {e}")
            return False

    def create_tag(
        self,
        version: str,
        message: Optional[str] = None,
        annotated: bool = True
    ) -> bool:
        """Create a Git tag with semantic versioning.
        
        Implements Requirement 18.8: Create Git tags with semantic versioning
        (e.g., v1.0.0, v1.1.0-beta).
        
        Args:
            version: Version string (e.g., "1.0.0", "1.1.0-beta")
            message: Optional tag message
            annotated: Whether to create an annotated tag
            
        Returns:
            True if successful, False otherwise
        """
        try:
            # Ensure version starts with 'v'
            if not version.startswith("v"):
                version = f"v{version}"

            # Create tag
            if annotated:
                tag_message = message or f"Release {version}"
                self._run_git_command(["tag", "-a", version, "-m", tag_message])
            else:
                self._run_git_command(["tag", version])

            logger.info(f"Created tag: {version}")
            return True

        except Exception as e:
            logger.error(f"Failed to create tag: {e}")
            return False

    def get_latest_tag(self) -> Optional[str]:
        """Get the most recent tag.
        
        Returns:
            Latest tag name or None if no tags exist
        """
        try:
            result = self._run_git_command(
                ["describe", "--tags", "--abbrev=0"],
                check=False
            )
            if result.returncode == 0:
                return result.stdout.strip()
            return None

        except Exception as e:
            logger.error(f"Failed to get latest tag: {e}")
            return None

    def _has_changes(self) -> bool:
        """Check if there are any changes in the working directory."""
        try:
            result = self._run_git_command(["status", "--porcelain"])
            return bool(result.stdout.strip())
        except Exception:
            return False

    def _has_staged_changes(self) -> bool:
        """Check if there are staged changes ready to commit."""
        try:
            result = self._run_git_command(["diff", "--cached", "--quiet"], check=False)
            return result.returncode != 0
        except Exception:
            return False

    def get_commit_history(self, limit: int = 10) -> List[Dict[str, str]]:
        """Get recent commit history.
        
        Args:
            limit: Maximum number of commits to retrieve
            
        Returns:
            List of commit dictionaries with hash, author, date, and message
        """
        try:
            result = self._run_git_command([
                "log",
                f"-{limit}",
                "--pretty=format:%H|%an|%ad|%s",
                "--date=iso"
            ])
            
            commits = []
            for line in result.stdout.strip().split("\n"):
                if line:
                    parts = line.split("|", 3)
                    if len(parts) == 4:
                        commits.append({
                            "hash": parts[0],
                            "author": parts[1],
                            "date": parts[2],
                            "message": parts[3]
                        })
            
            return commits

        except Exception as e:
            logger.error(f"Failed to get commit history: {e}")
            return []
