"""Sync orchestrated schema.

Revision ID: 033d61d95ac2
Revises: 6bfcfdc63375
Create Date: 2026-04-08 12:12:11.216627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033d61d95ac2'
down_revision = '6bfcfdc63375'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
