"""Add Artifact language and AgentExecution model

Revision ID: 6bfcfdc63375
Revises: 480bc123d459
Create Date: 2026-03-21 15:28:03.180002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfcfdc63375'
down_revision = '480bc123d459'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_type'), 'agent_executions', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_executions_project_id'), 'agent_executions', ['project_id'], unique=False)
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.add_column('approval_requests', sa.Column('stage', sa.String(length=64), nullable=True))
    op.add_column('approval_requests', sa.Column('reviewer_comment', sa.Text(), nullable=True))
    op.add_column('artifacts', sa.Column('language', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_artifacts_language'), 'artifacts', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_language'), table_name='artifacts')
    op.drop_column('artifacts', 'language')
    op.drop_column('approval_requests', 'reviewer_comment')
    op.drop_column('approval_requests', 'stage')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_agent_executions_project_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_type'), table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
